name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  gcc:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python3 tests/scripts/gen_random_tests.py
      - run: cmake --preset tests
      - run: cmake --build --preset tests
      - run: ctest --preset tests

  clang:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python3 tests/scripts/gen_random_tests.py
      - run: cmake --preset tests
      - run: cmake --build --preset tests
      - run: ctest --preset tests
